name: QtOpenGLProject

on:
  push:
    branches:
      - master
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential qt5-default libgl1-mesa-dev freeglut3-dev mesa-utils debhelper dh-make fakeroot

      - name: Build project
        run: |
          qmake
          make
          dpkg-buildpackage -us -uc

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets._GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets._GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ../qtopenglproject_1.0-1_amd64.deb
          asset_name: qtopenglproject_1.0-1_amd64.deb
          asset_content_type: application/octet-stream
  
